data_description: Perturbation-based Data Generation
n_observations: 10
image_dim: [480,640]
z_lim: [0.1,0.7] # Movement boundaries.
move_min: 0.1 # Minimum camera movement.
# Random object properties.
size: [100,200,300,400]
n_points: [3,4,5,6,7,8,9,10]
bez_rotate: [0.01, 0.05, 0.2]
bez_radius: [0.01, 0.05, 0.2, 0.5]
# Mask perturbations.
perturb: True
std_dev: 1 # See Eq. (20) from paper for details.